version: "3.7"
services:
  service:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
    restart: on-failure
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
volumes:
  data-volume: